In [2]:
import pandas as pd
import numpy as np 

In [3]:
frame = pd.read_csv("C:/Users/Dima/Desktop/MIP/modelling/ndvi_binned.csv")
frame

RegionName        Date  Year  Month  Day  \
0         QLD Condamine-Balonne  2006-01-15  2006      1   15   
1            NSW Barwon Darling  2006-01-15  2006      1   15   
2                    QLD Moonie  2006-01-15  2006      1   15   
3              NSW Murray Above  2006-01-15  2006      1   15   
4             NSW Lower Darling  2006-01-15  2006      1   15   
...                         ...         ...   ...    ...  ...   
1615                 NSW Gwydir  2020-12-15  2020     12   15   
1616                  NSW Namoi  2020-12-15  2020     12   15   
1617  NSW Macquarie-Castlereagh  2020-12-15  2020     12   15   
1618                NSW Lachlan  2020-12-15  2020     12   15   
1619           NSW Murrumbidgee  2020-12-15  2020     12   15   

      Water/Snow/Clouds  Bare Soil  Sparse Veg  Moderate Veg  Dense Veg  \
0              0.000000   0.000000    0.609082      0.295880   0.089419   
1              0.000000   0.000000    0.900919      0.096241   0.002840   
2              0.000000   0.000000    0.720358      0.275168   0.004474   
3              0.000000   0.000000    0.000000      0.452703   0.466216   
4              0.001614   0.000646    0.941879      0.055861   0.000000   
...                 ...        ...         ...           ...        ...   
1615           0.000000   0.000000    0.443023      0.305814   0.251163   
1616           0.000000   0.000000    0.250000      0.528631   0.221369   
1617           0.000000   0.000000    0.399707      0.414008   0.182985   
1618           0.000000   0.000612    0.497706      0.397675   0.102172   
1619           0.000000   0.000000    0.616195      0.220349   0.144792   

      Very Dense Veg  
0           0.005618  
1           0.000000  
2           0.000000  
3           0.081081  
4           0.000000  
...              ...  
1615        0.000000  
1616        0.000000  
1617        0.003300  
1618        0.001835  
1619        0.018663  

[1620 rows x 11 columns]

In [4]:
frame.Year.unique()

array([2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
       2017, 2018, 2019, 2020])

In [5]:
frame.Day.unique()

array([15])

In [6]:
frame.Month.unique()

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12])

In [7]:
def map_north(dates):
    if ((dates.Month == 9) and (dates.Day > 20)) or (dates.Month == 10):
        return "Planting"
    elif (dates.Month == 11) or (dates.Month == 12):
        return "Growing"
    elif (dates.Month == 1):
        return "Flowering"
    elif (dates.Month == 2) or (dates.Month == 3):
        return "Maturation"
    elif (dates.Month == 4):
        return "Harvesting"
    else:
        return "NotSeason"

In [8]:
def map_south(dates):
    if ((dates.Month == 10) and (dates.Day >= 15)) or (dates.Month == 11):
        return "Planting"
    elif (dates.Month == 12):
        return "Growing"
    elif (dates.Month == 1):
        return "Flowering"
    elif (dates.Month == 2) or (dates.Month == 3):
        return "Maturation"
    elif (dates.Month == 4) or (dates.Month == 5):
        return "Harvesting"
    else:
        return "NotSeason"

In [9]:
def season_mapping(frame):
    north = ["QLD Condamine-Balonne", "QLD Moonie" ,"QLD Border Rivers", "NSW Border Rivers", "NSW Barwon-Darling", "NSW Lower Darling", "NSW Macquarie-Castlereagh", "NSW Namoi", "NSW Gwydir"]
    # south = ["NSW Murrumbidgee", "NSW Lachlan", "NSW Murray Above"]

    if frame.RegionName in north:
        return map_north(frame)
    else:
        return map_south(frame)

In [10]:
frame["Season"] = frame[["RegionName", "Date", "Month", "Day"]].apply(season_mapping, axis = 1)
frame

RegionName        Date  Year  Month  Day  \
0         QLD Condamine-Balonne  2006-01-15  2006      1   15   
1            NSW Barwon Darling  2006-01-15  2006      1   15   
2                    QLD Moonie  2006-01-15  2006      1   15   
3              NSW Murray Above  2006-01-15  2006      1   15   
4             NSW Lower Darling  2006-01-15  2006      1   15   
...                         ...         ...   ...    ...  ...   
1615                 NSW Gwydir  2020-12-15  2020     12   15   
1616                  NSW Namoi  2020-12-15  2020     12   15   
1617  NSW Macquarie-Castlereagh  2020-12-15  2020     12   15   
1618                NSW Lachlan  2020-12-15  2020     12   15   
1619           NSW Murrumbidgee  2020-12-15  2020     12   15   

      Water/Snow/Clouds  Bare Soil  Sparse Veg  Moderate Veg  Dense Veg  \
0              0.000000   0.000000    0.609082      0.295880   0.089419   
1              0.000000   0.000000    0.900919      0.096241   0.002840   
2              0.000000   0.000000    0.720358      0.275168   0.004474   
3              0.000000   0.000000    0.000000      0.452703   0.466216   
4              0.001614   0.000646    0.941879      0.055861   0.000000   
...                 ...        ...         ...           ...        ...   
1615           0.000000   0.000000    0.443023      0.305814   0.251163   
1616           0.000000   0.000000    0.250000      0.528631   0.221369   
1617           0.000000   0.000000    0.399707      0.414008   0.182985   
1618           0.000000   0.000612    0.497706      0.397675   0.102172   
1619           0.000000   0.000000    0.616195      0.220349   0.144792   

      Very Dense Veg     Season  
0           0.005618  Flowering  
1           0.000000  Flowering  
2           0.000000  Flowering  
3           0.081081  Flowering  
4           0.000000  Flowering  
...              ...        ...  
1615        0.000000    Growing  
1616        0.000000    Growing  
1617        0.003300    Growing  
1618        0.001835    Growing  
1619        0.018663    Growing  

[1620 rows x 12 columns]

In [11]:
frames = frame[frame["Season"] != "NotSeason"].copy()
frames

RegionName        Date  Year  Month  Day  \
0         QLD Condamine-Balonne  2006-01-15  2006      1   15   
1            NSW Barwon Darling  2006-01-15  2006      1   15   
2                    QLD Moonie  2006-01-15  2006      1   15   
3              NSW Murray Above  2006-01-15  2006      1   15   
4             NSW Lower Darling  2006-01-15  2006      1   15   
...                         ...         ...   ...    ...  ...   
1615                 NSW Gwydir  2020-12-15  2020     12   15   
1616                  NSW Namoi  2020-12-15  2020     12   15   
1617  NSW Macquarie-Castlereagh  2020-12-15  2020     12   15   
1618                NSW Lachlan  2020-12-15  2020     12   15   
1619           NSW Murrumbidgee  2020-12-15  2020     12   15   

      Water/Snow/Clouds  Bare Soil  Sparse Veg  Moderate Veg  Dense Veg  \
0              0.000000   0.000000    0.609082      0.295880   0.089419   
1              0.000000   0.000000    0.900919      0.096241   0.002840   
2              0.000000   0.000000    0.720358      0.275168   0.004474   
3              0.000000   0.000000    0.000000      0.452703   0.466216   
4              0.001614   0.000646    0.941879      0.055861   0.000000   
...                 ...        ...         ...           ...        ...   
1615           0.000000   0.000000    0.443023      0.305814   0.251163   
1616           0.000000   0.000000    0.250000      0.528631   0.221369   
1617           0.000000   0.000000    0.399707      0.414008   0.182985   
1618           0.000000   0.000612    0.497706      0.397675   0.102172   
1619           0.000000   0.000000    0.616195      0.220349   0.144792   

      Very Dense Veg     Season  
0           0.005618  Flowering  
1           0.000000  Flowering  
2           0.000000  Flowering  
3           0.081081  Flowering  
4           0.000000  Flowering  
...              ...        ...  
1615        0.000000    Growing  
1616        0.000000    Growing  
1617        0.003300    Growing  
1618        0.001835    Growing  
1619        0.018663    Growing  

[1320 rows x 12 columns]

In [12]:
frames.rename(columns={"RegionName" : "Region"}, inplace = True)

In [13]:
frames.columns

Index(['Region', 'Date', 'Year', 'Month', 'Day', 'Water/Snow/Clouds',
       'Bare Soil', 'Sparse Veg', 'Moderate Veg', 'Dense Veg',
       'Very Dense Veg', 'Season'],
      dtype='object')

In [14]:
frames.groupby('Region')["Date"].count()

Region
NSW Barwon Darling           120
NSW Border Rivers            105
NSW Gwydir                   105
NSW Lachlan                  120
NSW Lower Darling            105
NSW Macquarie-Castlereagh    105
NSW Murray Above             120
NSW Murrumbidgee             120
NSW Namoi                    105
QLD Border Rivers            105
QLD Condamine-Balonne        105
QLD Moonie                   105
Name: Date, dtype: int64

In [15]:
frames.groupby(["Region"])[["Water/Snow/Clouds", "Bare Soil", "Sparse Veg", "Moderate Veg", "Dense Veg", "Very Dense Veg"]].mean()

Water/Snow/Clouds  Bare Soil  Sparse Veg  \
Region                                                                
NSW Barwon Darling                  0.000405   0.000656    0.713396   
NSW Border Rivers                   0.000000   0.000000    0.206145   
NSW Gwydir                          0.000022   0.000044    0.356999   
NSW Lachlan                         0.000168   0.000184    0.477266   
NSW Lower Darling                   0.002835   0.002091    0.860381   
NSW Macquarie-Castlereagh           0.000000   0.000003    0.356830   
NSW Murray Above                    0.000000   0.000000    0.001464   
NSW Murrumbidgee                    0.000000   0.000166    0.478908   
NSW Namoi                           0.000106   0.000073    0.226310   
QLD Border Rivers                   0.000000   0.000036    0.275431   
QLD Condamine-Balonne               0.000103   0.000225    0.448493   
QLD Moonie                          0.000000   0.000021    0.510728   

                           Moderate Veg  Dense Veg  Very Dense Veg  
Region                                                              
NSW Barwon Darling             0.272693   0.012654        0.000196  
NSW Border Rivers              0.434716   0.330011        0.029127  
NSW Gwydir                     0.387896   0.235581        0.019457  
NSW Lachlan                    0.383583   0.119868        0.018930  
NSW Lower Darling              0.132734   0.001953        0.000006  
NSW Macquarie-Castlereagh      0.428830   0.196508        0.017829  
NSW Murray Above               0.158277   0.486993        0.353266  
NSW Murrumbidgee               0.307019   0.168809        0.045098  
NSW Namoi                      0.479449   0.276370        0.017691  
QLD Border Rivers              0.523159   0.198722        0.002652  
QLD Condamine-Balonne          0.423181   0.121030        0.006969  
QLD Moonie                     0.406562   0.082582        0.000107

In [16]:
frames.to_csv("ndvi_data.csv", index = False)